export const allProducts = {
  data: [
    {
      id: 1,
      attributes: {
        name: "Eco-Friendly Tote Bag",
        price: 200000,
        category: "newArrivals",
        createdAt: "2023-02-13T03:25:20.626Z",
        updatedAt: "2023-02-22T14:02:46.660Z",
        publishedAt: "2023-02-13T03:35:29.221Z",
        shortDesc: "Professional-grade camera for stunning photos.",
        longDesc:
          "Take your photography to the next level with our professional-grade camera. With advanced features and a sleek design, this camera produces stunning, high-quality photos that are sure to impress. Whether you're a professional photographer or just starting out, our camera will help you capture the perfect shot every time. Upgrade your photography game with our professional-grade camera.",
        image: {
          data: [
            {
              id: 18,
              attributes: {
                name: "joren-aranas-nmuyqgSOpEE-unsplash.jpg",
                alternativeText: null,
                caption: null,
                width: 4366,
                height: 6542,
                formats: {
                  thumbnail: {
                    name: "thumbnail_joren-aranas-nmuyqgSOpEE-unsplash.jpg",
                    hash: "thumbnail_joren_aranas_nmuyqg_S_Op_EE_unsplash_17e9d7a2f3",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 104,
                    height: 156,
                    size: 2.76,
                    url: "/uploads/thumbnail_joren_aranas_nmuyqg_S_Op_EE_unsplash_17e9d7a2f3.jpg",
                  },
                  large: {
                    name: "large_joren-aranas-nmuyqgSOpEE-unsplash.jpg",
                    hash: "large_joren_aranas_nmuyqg_S_Op_EE_unsplash_17e9d7a2f3",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 667,
                    height: 1000,
                    size: 38.39,
                    url: "/uploads/large_joren_aranas_nmuyqg_S_Op_EE_unsplash_17e9d7a2f3.jpg",
                  },
                  medium: {
                    name: "medium_joren-aranas-nmuyqgSOpEE-unsplash.jpg",
                    hash: "medium_joren_aranas_nmuyqg_S_Op_EE_unsplash_17e9d7a2f3",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 500,
                    height: 750,
                    size: 25.1,
                    url: "/uploads/medium_joren_aranas_nmuyqg_S_Op_EE_unsplash_17e9d7a2f3.jpg",
                  },
                  small: {
                    name: "small_joren-aranas-nmuyqgSOpEE-unsplash.jpg",
                    hash: "small_joren_aranas_nmuyqg_S_Op_EE_unsplash_17e9d7a2f3",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 334,
                    height: 500,
                    size: 14.2,
                    url: "/uploads/small_joren_aranas_nmuyqg_S_Op_EE_unsplash_17e9d7a2f3.jpg",
                  },
                },
                hash: "joren_aranas_nmuyqg_S_Op_EE_unsplash_17e9d7a2f3",
                ext: ".jpg",
                mime: "image/jpeg",
                size: 2437.2,
                url: "/uploads/joren_aranas_nmuyqg_S_Op_EE_unsplash_17e9d7a2f3.jpg",
                previewUrl: null,
                provider: "local",
                provider_metadata: null,
                createdAt: "2023-02-13T03:17:33.819Z",
                updatedAt: "2023-02-13T03:24:53.712Z",
              },
            },
          ],
        },
      },
    },
    {
      id: 3,
      attributes: {
        name: "Smart Fitness Tracker",
        price: 150000,
        category: "newArrivals",
        createdAt: "2023-02-13T03:27:26.971Z",
        updatedAt: "2023-02-22T14:06:13.043Z",
        publishedAt: "2023-02-13T03:35:47.509Z",
        shortDesc: "Professional-grade hair styling tools.",
        longDesc:
          "Achieve salon-quality hair styling results at home with our professional-grade hair styling tools. Our line of hair dryers, curling irons and straighteners are designed to provide high performance, precision and durability. With adjustable temperature settings and fast heating times, you can create the perfect style in no time. Elevate your hair styling game with our professional-grade tools.",
        image: {
          data: [
            {
              id: 16,
              attributes: {
                name: "luobulinka-FO4mQZi1c0M-unsplash.jpg",
                alternativeText: null,
                caption: null,
                width: 4024,
                height: 6048,
                formats: {
                  thumbnail: {
                    name: "thumbnail_luobulinka-FO4mQZi1c0M-unsplash.jpg",
                    hash: "thumbnail_luobulinka_FO_4m_Q_Zi1c0_M_unsplash_71bed8de79",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 104,
                    height: 156,
                    size: 4.86,
                    url: "/uploads/thumbnail_luobulinka_FO_4m_Q_Zi1c0_M_unsplash_71bed8de79.jpg",
                  },
                  medium: {
                    name: "medium_luobulinka-FO4mQZi1c0M-unsplash.jpg",
                    hash: "medium_luobulinka_FO_4m_Q_Zi1c0_M_unsplash_71bed8de79",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 499,
                    height: 750,
                    size: 65.42,
                    url: "/uploads/medium_luobulinka_FO_4m_Q_Zi1c0_M_unsplash_71bed8de79.jpg",
                  },
                  small: {
                    name: "small_luobulinka-FO4mQZi1c0M-unsplash.jpg",
                    hash: "small_luobulinka_FO_4m_Q_Zi1c0_M_unsplash_71bed8de79",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 333,
                    height: 500,
                    size: 33.42,
                    url: "/uploads/small_luobulinka_FO_4m_Q_Zi1c0_M_unsplash_71bed8de79.jpg",
                  },
                  large: {
                    name: "large_luobulinka-FO4mQZi1c0M-unsplash.jpg",
                    hash: "large_luobulinka_FO_4m_Q_Zi1c0_M_unsplash_71bed8de79",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 665,
                    height: 1000,
                    size: 104.65,
                    url: "/uploads/large_luobulinka_FO_4m_Q_Zi1c0_M_unsplash_71bed8de79.jpg",
                  },
                },
                hash: "luobulinka_FO_4m_Q_Zi1c0_M_unsplash_71bed8de79",
                ext: ".jpg",
                mime: "image/jpeg",
                size: 5529.83,
                url: "/uploads/luobulinka_FO_4m_Q_Zi1c0_M_unsplash_71bed8de79.jpg",
                previewUrl: null,
                provider: "local",
                provider_metadata: null,
                createdAt: "2023-02-13T03:17:32.918Z",
                updatedAt: "2023-02-13T03:27:18.044Z",
              },
            },
          ],
        },
      },
    },
    {
      id: 4,
      attributes: {
        name: "Stylish Backpack",
        price: 150000,
        category: "newArrivals",
        createdAt: "2023-02-13T03:29:43.600Z",
        updatedAt: "2023-02-22T14:06:33.783Z",
        publishedAt: "2023-02-13T03:35:51.538Z",
        shortDesc: "Compact and versatile food processor.",
        longDesc:
          "Save time and effort in the kitchen with our compact and versatile food processor. With multiple functions, including chopping, slicing, shredding and pureeing, this food processor makes meal prep a breeze. The compact size and easy-to-use controls make it perfect for any kitchen, big or small. Get the perfect cut every time with our food processor.",
        image: {
          data: [
            {
              id: 15,
              attributes: {
                name: "ivan-dodig-R21SyyJDFgc-unsplash.jpg",
                alternativeText: null,
                caption: null,
                width: 4000,
                height: 5333,
                formats: {
                  thumbnail: {
                    name: "thumbnail_ivan-dodig-R21SyyJDFgc-unsplash.jpg",
                    hash: "thumbnail_ivan_dodig_R21_Syy_JD_Fgc_unsplash_7e90392296",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 117,
                    height: 156,
                    size: 4.52,
                    url: "/uploads/thumbnail_ivan_dodig_R21_Syy_JD_Fgc_unsplash_7e90392296.jpg",
                  },
                  medium: {
                    name: "medium_ivan-dodig-R21SyyJDFgc-unsplash.jpg",
                    hash: "medium_ivan_dodig_R21_Syy_JD_Fgc_unsplash_7e90392296",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 563,
                    height: 750,
                    size: 48.56,
                    url: "/uploads/medium_ivan_dodig_R21_Syy_JD_Fgc_unsplash_7e90392296.jpg",
                  },
                  small: {
                    name: "small_ivan-dodig-R21SyyJDFgc-unsplash.jpg",
                    hash: "small_ivan_dodig_R21_Syy_JD_Fgc_unsplash_7e90392296",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 375,
                    height: 500,
                    size: 25.38,
                    url: "/uploads/small_ivan_dodig_R21_Syy_JD_Fgc_unsplash_7e90392296.jpg",
                  },
                  large: {
                    name: "large_ivan-dodig-R21SyyJDFgc-unsplash.jpg",
                    hash: "large_ivan_dodig_R21_Syy_JD_Fgc_unsplash_7e90392296",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 750,
                    height: 1000,
                    size: 77.61,
                    url: "/uploads/large_ivan_dodig_R21_Syy_JD_Fgc_unsplash_7e90392296.jpg",
                  },
                },
                hash: "ivan_dodig_R21_Syy_JD_Fgc_unsplash_7e90392296",
                ext: ".jpg",
                mime: "image/jpeg",
                size: 2761.21,
                url: "/uploads/ivan_dodig_R21_Syy_JD_Fgc_unsplash_7e90392296.jpg",
                previewUrl: null,
                provider: "local",
                provider_metadata: null,
                createdAt: "2023-02-13T03:17:32.077Z",
                updatedAt: "2023-02-13T03:17:32.077Z",
              },
            },
          ],
        },
      },
    },
    {
      id: 5,
      attributes: {
        name: "Portable Bluetooth Speaker",
        price: 500000,
        category: "newArrivals",
        createdAt: "2023-02-13T03:30:23.830Z",
        updatedAt: "2023-02-22T14:05:17.033Z",
        publishedAt: "2023-02-13T03:35:37.543Z",
        shortDesc: "Smart lock for easy and secure access.",
        longDesc:
          "Say goodbye to keys and hello to convenience with our smart lock. Easily manage access to your home, office or rental property with our smartphone app, keypad or voice assistant. With multiple levels of security, including end-to-end encryption and two-factor authentication, our smart lock provides added peace of mind. Get secure access control in a snap with our smart lock.",
        image: {
          data: [
            {
              id: 14,
              attributes: {
                name: "rafaella-mendes-diniz-AoL-mVxprmk-unsplash.jpg",
                alternativeText: null,
                caption: null,
                width: 3456,
                height: 5184,
                formats: {
                  thumbnail: {
                    name: "thumbnail_rafaella-mendes-diniz-AoL-mVxprmk-unsplash.jpg",
                    hash: "thumbnail_rafaella_mendes_diniz_Ao_L_m_Vxprmk_unsplash_2e0e1302a7",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 104,
                    height: 156,
                    size: 3.75,
                    url: "/uploads/thumbnail_rafaella_mendes_diniz_Ao_L_m_Vxprmk_unsplash_2e0e1302a7.jpg",
                  },
                  medium: {
                    name: "medium_rafaella-mendes-diniz-AoL-mVxprmk-unsplash.jpg",
                    hash: "medium_rafaella_mendes_diniz_Ao_L_m_Vxprmk_unsplash_2e0e1302a7",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 500,
                    height: 750,
                    size: 40.93,
                    url: "/uploads/medium_rafaella_mendes_diniz_Ao_L_m_Vxprmk_unsplash_2e0e1302a7.jpg",
                  },
                  small: {
                    name: "small_rafaella-mendes-diniz-AoL-mVxprmk-unsplash.jpg",
                    hash: "small_rafaella_mendes_diniz_Ao_L_m_Vxprmk_unsplash_2e0e1302a7",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 333,
                    height: 500,
                    size: 20.73,
                    url: "/uploads/small_rafaella_mendes_diniz_Ao_L_m_Vxprmk_unsplash_2e0e1302a7.jpg",
                  },
                  large: {
                    name: "large_rafaella-mendes-diniz-AoL-mVxprmk-unsplash.jpg",
                    hash: "large_rafaella_mendes_diniz_Ao_L_m_Vxprmk_unsplash_2e0e1302a7",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 667,
                    height: 1000,
                    size: 67.3,
                    url: "/uploads/large_rafaella_mendes_diniz_Ao_L_m_Vxprmk_unsplash_2e0e1302a7.jpg",
                  },
                },
                hash: "rafaella_mendes_diniz_Ao_L_m_Vxprmk_unsplash_2e0e1302a7",
                ext: ".jpg",
                mime: "image/jpeg",
                size: 1403.5,
                url: "/uploads/rafaella_mendes_diniz_Ao_L_m_Vxprmk_unsplash_2e0e1302a7.jpg",
                previewUrl: null,
                provider: "local",
                provider_metadata: null,
                createdAt: "2023-02-13T03:17:29.573Z",
                updatedAt: "2023-02-13T03:17:29.573Z",
              },
            },
          ],
        },
      },
    },
    {
      id: 6,
      attributes: {
        name: "Tumbler Unik",
        price: 278000,
        category: "newArrivals",
        createdAt: "2023-02-13T03:32:50.437Z",
        updatedAt: "2023-02-22T14:07:43.238Z",
        publishedAt: "2023-02-13T03:33:11.998Z",
        shortDesc: "All-natural skincare set for radiant skin.",
        longDesc:
          "Pamper your skin with our all-natural skincare set. Our set includes a cleanser, toner, serum and moisturizer, all made with natural and organic ingredients. The set is designed to hydrate, nourish and brighten your skin, leaving you with a healthy and radiant glow. Get the perfect skin with our all-natural skincare set.",
        image: {
          data: [
            {
              id: 13,
              attributes: {
                name: "ilya-pavlov-xE87C_OvVO4-unsplash.jpg",
                alternativeText: null,
                caption: null,
                width: 3543,
                height: 2365,
                formats: {
                  thumbnail: {
                    name: "thumbnail_ilya-pavlov-xE87C_OvVO4-unsplash.jpg",
                    hash: "thumbnail_ilya_pavlov_x_E87_C_Ov_VO_4_unsplash_66edce465e",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 234,
                    height: 156,
                    size: 6.9,
                    url: "/uploads/thumbnail_ilya_pavlov_x_E87_C_Ov_VO_4_unsplash_66edce465e.jpg",
                  },
                  medium: {
                    name: "medium_ilya-pavlov-xE87C_OvVO4-unsplash.jpg",
                    hash: "medium_ilya_pavlov_x_E87_C_Ov_VO_4_unsplash_66edce465e",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 750,
                    height: 501,
                    size: 42.58,
                    url: "/uploads/medium_ilya_pavlov_x_E87_C_Ov_VO_4_unsplash_66edce465e.jpg",
                  },
                  small: {
                    name: "small_ilya-pavlov-xE87C_OvVO4-unsplash.jpg",
                    hash: "small_ilya_pavlov_x_E87_C_Ov_VO_4_unsplash_66edce465e",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 500,
                    height: 334,
                    size: 21.99,
                    url: "/uploads/small_ilya_pavlov_x_E87_C_Ov_VO_4_unsplash_66edce465e.jpg",
                  },
                  large: {
                    name: "large_ilya-pavlov-xE87C_OvVO4-unsplash.jpg",
                    hash: "large_ilya_pavlov_x_E87_C_Ov_VO_4_unsplash_66edce465e",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 1000,
                    height: 667,
                    size: 70.67,
                    url: "/uploads/large_ilya_pavlov_x_E87_C_Ov_VO_4_unsplash_66edce465e.jpg",
                  },
                },
                hash: "ilya_pavlov_x_E87_C_Ov_VO_4_unsplash_66edce465e",
                ext: ".jpg",
                mime: "image/jpeg",
                size: 954.86,
                url: "/uploads/ilya_pavlov_x_E87_C_Ov_VO_4_unsplash_66edce465e.jpg",
                previewUrl: null,
                provider: "local",
                provider_metadata: null,
                createdAt: "2023-02-13T03:17:29.553Z",
                updatedAt: "2023-02-13T03:17:29.553Z",
              },
            },
          ],
        },
      },
    },
    {
      id: 7,
      attributes: {
        name: "Bantal Nyaman",
        price: 150000,
        category: "bestSellers",
        createdAt: "2023-02-13T03:33:48.602Z",
        updatedAt: "2023-02-22T14:01:59.189Z",
        publishedAt: "2023-02-13T03:35:22.783Z",
        shortDesc: "Smart thermostat for efficient home energy use.",
        longDesc:
          "Upgrade your home's energy efficiency with our smart thermostat. With advanced sensors and intelligent controls, this thermostat automatically adjusts your home's temperature to your preferences, saving you energy and money. Use our app to control your thermostat from anywhere and receive alerts when you need to change your filter or schedule maintenance. Take control of your energy use today with our smart thermostat.",
        image: {
          data: [
            {
              id: 12,
              attributes: {
                name: "naeim-jafari-6Xai7XxOgBc-unsplash.jpg",
                alternativeText: null,
                caption: null,
                width: 1969,
                height: 2953,
                formats: {
                  thumbnail: {
                    name: "thumbnail_naeim-jafari-6Xai7XxOgBc-unsplash.jpg",
                    hash: "thumbnail_naeim_jafari_6_Xai7_Xx_Og_Bc_unsplash_531712da87",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 104,
                    height: 156,
                    size: 4.28,
                    url: "/uploads/thumbnail_naeim_jafari_6_Xai7_Xx_Og_Bc_unsplash_531712da87.jpg",
                  },
                  medium: {
                    name: "medium_naeim-jafari-6Xai7XxOgBc-unsplash.jpg",
                    hash: "medium_naeim_jafari_6_Xai7_Xx_Og_Bc_unsplash_531712da87",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 500,
                    height: 750,
                    size: 52.83,
                    url: "/uploads/medium_naeim_jafari_6_Xai7_Xx_Og_Bc_unsplash_531712da87.jpg",
                  },
                  small: {
                    name: "small_naeim-jafari-6Xai7XxOgBc-unsplash.jpg",
                    hash: "small_naeim_jafari_6_Xai7_Xx_Og_Bc_unsplash_531712da87",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 333,
                    height: 500,
                    size: 26.48,
                    url: "/uploads/small_naeim_jafari_6_Xai7_Xx_Og_Bc_unsplash_531712da87.jpg",
                  },
                  large: {
                    name: "large_naeim-jafari-6Xai7XxOgBc-unsplash.jpg",
                    hash: "large_naeim_jafari_6_Xai7_Xx_Og_Bc_unsplash_531712da87",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 667,
                    height: 1000,
                    size: 89.3,
                    url: "/uploads/large_naeim_jafari_6_Xai7_Xx_Og_Bc_unsplash_531712da87.jpg",
                  },
                },
                hash: "naeim_jafari_6_Xai7_Xx_Og_Bc_unsplash_531712da87",
                ext: ".jpg",
                mime: "image/jpeg",
                size: 899.87,
                url: "/uploads/naeim_jafari_6_Xai7_Xx_Og_Bc_unsplash_531712da87.jpg",
                previewUrl: null,
                provider: "local",
                provider_metadata: null,
                createdAt: "2023-02-13T03:17:28.260Z",
                updatedAt: "2023-02-13T03:17:28.260Z",
              },
            },
          ],
        },
      },
    },
    {
      id: 8,
      attributes: {
        name: "Jam Tangan Elegan",
        price: 340000,
        category: "bestSellers",
        createdAt: "2023-02-13T03:34:27.771Z",
        updatedAt: "2023-02-22T14:03:33.058Z",
        publishedAt: "2023-02-13T03:35:32.691Z",
        shortDesc: "Compact and powerful portable charger.",
        longDesc:
          "Stay connected on the go with our compact and powerful portable charger. With a high-capacity battery, this charger can keep your devices powered up and ready to go wherever you are. Plus, its compact size makes it easy to carry in your pocket or bag, so you'll always have power at your fingertips. Stay connected and stay charged with our portable charger.",
        image: {
          data: [
            {
              id: 11,
              attributes: {
                name: "huston-wilson-WyDr1KFS23Y-unsplash.jpg",
                alternativeText: null,
                caption: null,
                width: 3168,
                height: 4752,
                formats: {
                  thumbnail: {
                    name: "thumbnail_huston-wilson-WyDr1KFS23Y-unsplash.jpg",
                    hash: "thumbnail_huston_wilson_Wy_Dr1_KFS_23_Y_unsplash_0490ca3a08",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 104,
                    height: 156,
                    size: 3.58,
                    url: "/uploads/thumbnail_huston_wilson_Wy_Dr1_KFS_23_Y_unsplash_0490ca3a08.jpg",
                  },
                  medium: {
                    name: "medium_huston-wilson-WyDr1KFS23Y-unsplash.jpg",
                    hash: "medium_huston_wilson_Wy_Dr1_KFS_23_Y_unsplash_0490ca3a08",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 500,
                    height: 750,
                    size: 40.85,
                    url: "/uploads/medium_huston_wilson_Wy_Dr1_KFS_23_Y_unsplash_0490ca3a08.jpg",
                  },
                  small: {
                    name: "small_huston-wilson-WyDr1KFS23Y-unsplash.jpg",
                    hash: "small_huston_wilson_Wy_Dr1_KFS_23_Y_unsplash_0490ca3a08",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 333,
                    height: 500,
                    size: 20.79,
                    url: "/uploads/small_huston_wilson_Wy_Dr1_KFS_23_Y_unsplash_0490ca3a08.jpg",
                  },
                  large: {
                    name: "large_huston-wilson-WyDr1KFS23Y-unsplash.jpg",
                    hash: "large_huston_wilson_Wy_Dr1_KFS_23_Y_unsplash_0490ca3a08",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 667,
                    height: 1000,
                    size: 65.82,
                    url: "/uploads/large_huston_wilson_Wy_Dr1_KFS_23_Y_unsplash_0490ca3a08.jpg",
                  },
                },
                hash: "huston_wilson_Wy_Dr1_KFS_23_Y_unsplash_0490ca3a08",
                ext: ".jpg",
                mime: "image/jpeg",
                size: 1275.8,
                url: "/uploads/huston_wilson_Wy_Dr1_KFS_23_Y_unsplash_0490ca3a08.jpg",
                previewUrl: null,
                provider: "local",
                provider_metadata: null,
                createdAt: "2023-02-13T03:17:27.830Z",
                updatedAt: "2023-02-13T03:17:27.830Z",
              },
            },
          ],
        },
      },
    },
    {
      id: 9,
      attributes: {
        name: "Sepatu Sneakers Trendy",
        price: 500000,
        category: "bestSellers",
        createdAt: "2023-02-13T03:35:07.882Z",
        updatedAt: "2023-02-22T14:05:52.732Z",
        publishedAt: "2023-02-13T03:35:43.797Z",
        shortDesc: "Stylish and comfortable walking shoes.",
        longDesc:
          "Walk in comfort and style with our walking shoes. Made with breathable and lightweight materials, these shoes provide support and cushioning for your feet. The stylish design means they can be worn with a variety of outfits, making them the perfect choice for daily wear or long walks. Get the best of both worlds with our walking shoes.",
        image: {
          data: [
            {
              id: 10,
              attributes: {
                name: "alex-hddife-6wWiZlA2n0Q-unsplash.jpg",
                alternativeText: null,
                caption: null,
                width: 3264,
                height: 4912,
                formats: {
                  thumbnail: {
                    name: "thumbnail_alex-hddife-6wWiZlA2n0Q-unsplash.jpg",
                    hash: "thumbnail_alex_hddife_6w_Wi_Zl_A2n0_Q_unsplash_96c2b67d6d",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 104,
                    height: 156,
                    size: 2.37,
                    url: "/uploads/thumbnail_alex_hddife_6w_Wi_Zl_A2n0_Q_unsplash_96c2b67d6d.jpg",
                  },
                  large: {
                    name: "large_alex-hddife-6wWiZlA2n0Q-unsplash.jpg",
                    hash: "large_alex_hddife_6w_Wi_Zl_A2n0_Q_unsplash_96c2b67d6d",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 664,
                    height: 1000,
                    size: 42.62,
                    url: "/uploads/large_alex_hddife_6w_Wi_Zl_A2n0_Q_unsplash_96c2b67d6d.jpg",
                  },
                  medium: {
                    name: "medium_alex-hddife-6wWiZlA2n0Q-unsplash.jpg",
                    hash: "medium_alex_hddife_6w_Wi_Zl_A2n0_Q_unsplash_96c2b67d6d",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 498,
                    height: 750,
                    size: 27.41,
                    url: "/uploads/medium_alex_hddife_6w_Wi_Zl_A2n0_Q_unsplash_96c2b67d6d.jpg",
                  },
                  small: {
                    name: "small_alex-hddife-6wWiZlA2n0Q-unsplash.jpg",
                    hash: "small_alex_hddife_6w_Wi_Zl_A2n0_Q_unsplash_96c2b67d6d",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 332,
                    height: 500,
                    size: 14.4,
                    url: "/uploads/small_alex_hddife_6w_Wi_Zl_A2n0_Q_unsplash_96c2b67d6d.jpg",
                  },
                },
                hash: "alex_hddife_6w_Wi_Zl_A2n0_Q_unsplash_96c2b67d6d",
                ext: ".jpg",
                mime: "image/jpeg",
                size: 558.45,
                url: "/uploads/alex_hddife_6w_Wi_Zl_A2n0_Q_unsplash_96c2b67d6d.jpg",
                previewUrl: null,
                provider: "local",
                provider_metadata: null,
                createdAt: "2023-02-13T03:17:27.151Z",
                updatedAt: "2023-02-13T03:17:27.151Z",
              },
            },
          ],
        },
      },
    },
    {
      id: 10,
      attributes: {
        name: "Alat Tulis Set",
        price: 340000,
        category: "bestSellers",
        createdAt: "2023-02-13T03:36:38.977Z",
        updatedAt: "2023-02-22T14:01:40.785Z",
        publishedAt: "2023-02-13T03:36:40.574Z",
        shortDesc: "High-quality noise-cancelling headphones.",
        longDesc:
          "Immerse yourself in your favorite music without any distractions with our high-quality noise-cancelling headphones. These headphones are engineered to provide superior sound quality while reducing ambient noise, making them perfect for use in a variety of settings. With long-lasting battery life, comfortable fit, and convenient controls, our headphones will quickly become your go-to choice for a better listening experience.",
        image: {
          data: [
            {
              id: 9,
              attributes: {
                name: "radu-florin-OP8655xgBjo-unsplash.jpg",
                alternativeText: null,
                caption: null,
                width: 4000,
                height: 6000,
                formats: {
                  thumbnail: {
                    name: "thumbnail_radu-florin-OP8655xgBjo-unsplash.jpg",
                    hash: "thumbnail_radu_florin_OP_8655xg_Bjo_unsplash_3d43ccbac9",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 104,
                    height: 156,
                    size: 2.99,
                    url: "/uploads/thumbnail_radu_florin_OP_8655xg_Bjo_unsplash_3d43ccbac9.jpg",
                  },
                  large: {
                    name: "large_radu-florin-OP8655xgBjo-unsplash.jpg",
                    hash: "large_radu_florin_OP_8655xg_Bjo_unsplash_3d43ccbac9",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 667,
                    height: 1000,
                    size: 54,
                    url: "/uploads/large_radu_florin_OP_8655xg_Bjo_unsplash_3d43ccbac9.jpg",
                  },
                  medium: {
                    name: "medium_radu-florin-OP8655xgBjo-unsplash.jpg",
                    hash: "medium_radu_florin_OP_8655xg_Bjo_unsplash_3d43ccbac9",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 500,
                    height: 750,
                    size: 33.49,
                    url: "/uploads/medium_radu_florin_OP_8655xg_Bjo_unsplash_3d43ccbac9.jpg",
                  },
                  small: {
                    name: "small_radu-florin-OP8655xgBjo-unsplash.jpg",
                    hash: "small_radu_florin_OP_8655xg_Bjo_unsplash_3d43ccbac9",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 333,
                    height: 500,
                    size: 17.41,
                    url: "/uploads/small_radu_florin_OP_8655xg_Bjo_unsplash_3d43ccbac9.jpg",
                  },
                },
                hash: "radu_florin_OP_8655xg_Bjo_unsplash_3d43ccbac9",
                ext: ".jpg",
                mime: "image/jpeg",
                size: 2460.18,
                url: "/uploads/radu_florin_OP_8655xg_Bjo_unsplash_3d43ccbac9.jpg",
                previewUrl: null,
                provider: "local",
                provider_metadata: null,
                createdAt: "2023-02-13T03:17:22.618Z",
                updatedAt: "2023-02-13T03:17:22.618Z",
              },
            },
          ],
        },
      },
    },
    {
      id: 11,
      attributes: {
        name: "Kotak Pensil Unik",
        price: 100000,
        category: "bestSellers",
        createdAt: "2023-02-13T03:37:44.307Z",
        updatedAt: "2023-02-22T14:04:57.739Z",
        publishedAt: "2023-02-13T03:38:23.622Z",
        shortDesc: "Handcrafted leather wallet with RFID protection.",
        longDesc:
          "Keep your cards and cash safe with our handcrafted leather wallet. Made with the finest materials and meticulous attention to detail, this wallet is both stylish and durable. It also features RFID protection, which blocks attempts to scan your credit and debit cards, providing peace of mind and added security. Upgrade your wallet and keep your valuables safe with our leather wallet.",
        image: {
          data: [
            {
              id: 8,
              attributes: {
                name: "olga-zabegina-A3MleA0jtoE-unsplash.jpg",
                alternativeText: null,
                caption: null,
                width: 2700,
                height: 3600,
                formats: {
                  thumbnail: {
                    name: "thumbnail_olga-zabegina-A3MleA0jtoE-unsplash.jpg",
                    hash: "thumbnail_olga_zabegina_A3_Mle_A0jto_E_unsplash_cb7f2cb434",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 117,
                    height: 156,
                    size: 1.99,
                    url: "/uploads/thumbnail_olga_zabegina_A3_Mle_A0jto_E_unsplash_cb7f2cb434.jpg",
                  },
                  large: {
                    name: "large_olga-zabegina-A3MleA0jtoE-unsplash.jpg",
                    hash: "large_olga_zabegina_A3_Mle_A0jto_E_unsplash_cb7f2cb434",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 750,
                    height: 1000,
                    size: 44.75,
                    url: "/uploads/large_olga_zabegina_A3_Mle_A0jto_E_unsplash_cb7f2cb434.jpg",
                  },
                  small: {
                    name: "small_olga-zabegina-A3MleA0jtoE-unsplash.jpg",
                    hash: "small_olga_zabegina_A3_Mle_A0jto_E_unsplash_cb7f2cb434",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 375,
                    height: 500,
                    size: 10.63,
                    url: "/uploads/small_olga_zabegina_A3_Mle_A0jto_E_unsplash_cb7f2cb434.jpg",
                  },
                  medium: {
                    name: "medium_olga-zabegina-A3MleA0jtoE-unsplash.jpg",
                    hash: "medium_olga_zabegina_A3_Mle_A0jto_E_unsplash_cb7f2cb434",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 563,
                    height: 750,
                    size: 23.44,
                    url: "/uploads/medium_olga_zabegina_A3_Mle_A0jto_E_unsplash_cb7f2cb434.jpg",
                  },
                },
                hash: "olga_zabegina_A3_Mle_A0jto_E_unsplash_cb7f2cb434",
                ext: ".jpg",
                mime: "image/jpeg",
                size: 902.05,
                url: "/uploads/olga_zabegina_A3_Mle_A0jto_E_unsplash_cb7f2cb434.jpg",
                previewUrl: null,
                provider: "local",
                provider_metadata: null,
                createdAt: "2023-02-13T03:17:20.608Z",
                updatedAt: "2023-02-13T03:17:20.608Z",
              },
            },
          ],
        },
      },
    },
    {
      id: 12,
      attributes: {
        name: "T-Shirt Berkualitas",
        price: 220000,
        category: "bestSellers",
        createdAt: "2023-02-13T03:39:18.357Z",
        updatedAt: "2023-02-22T14:06:50.722Z",
        publishedAt: "2023-02-13T03:39:19.731Z",
        shortDesc: "Ultra-soft bamboo bed sheets.",
        longDesc:
          "Sleep in comfort and style with our ultra-soft bamboo bed sheets. Made with eco-friendly and sustainable materials, these sheets are naturally hypoallergenic, moisture-wicking and temperature-regulating. The luxurious and silky texture provides a comfortable and restful night's sleep. Elevate your bedding with our bamboo bed sheets.",
        image: {
          data: [
            {
              id: 7,
              attributes: {
                name: "atikh-bana-_KaMTEmJnxY-unsplash.jpg",
                alternativeText: null,
                caption: null,
                width: 5616,
                height: 3744,
                formats: {
                  thumbnail: {
                    name: "thumbnail_atikh-bana-_KaMTEmJnxY-unsplash.jpg",
                    hash: "thumbnail_atikh_bana_Ka_MT_Em_Jnx_Y_unsplash_df2f9e797a",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 234,
                    height: 156,
                    size: 6.11,
                    url: "/uploads/thumbnail_atikh_bana_Ka_MT_Em_Jnx_Y_unsplash_df2f9e797a.jpg",
                  },
                  large: {
                    name: "large_atikh-bana-_KaMTEmJnxY-unsplash.jpg",
                    hash: "large_atikh_bana_Ka_MT_Em_Jnx_Y_unsplash_df2f9e797a",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 1000,
                    height: 667,
                    size: 65.35,
                    url: "/uploads/large_atikh_bana_Ka_MT_Em_Jnx_Y_unsplash_df2f9e797a.jpg",
                  },
                  medium: {
                    name: "medium_atikh-bana-_KaMTEmJnxY-unsplash.jpg",
                    hash: "medium_atikh_bana_Ka_MT_Em_Jnx_Y_unsplash_df2f9e797a",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 750,
                    height: 500,
                    size: 41.18,
                    url: "/uploads/medium_atikh_bana_Ka_MT_Em_Jnx_Y_unsplash_df2f9e797a.jpg",
                  },
                  small: {
                    name: "small_atikh-bana-_KaMTEmJnxY-unsplash.jpg",
                    hash: "small_atikh_bana_Ka_MT_Em_Jnx_Y_unsplash_df2f9e797a",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 500,
                    height: 333,
                    size: 20.77,
                    url: "/uploads/small_atikh_bana_Ka_MT_Em_Jnx_Y_unsplash_df2f9e797a.jpg",
                  },
                },
                hash: "atikh_bana_Ka_MT_Em_Jnx_Y_unsplash_df2f9e797a",
                ext: ".jpg",
                mime: "image/jpeg",
                size: 2076.77,
                url: "/uploads/atikh_bana_Ka_MT_Em_Jnx_Y_unsplash_df2f9e797a.jpg",
                previewUrl: null,
                provider: "local",
                provider_metadata: null,
                createdAt: "2023-02-13T03:17:20.345Z",
                updatedAt: "2023-02-13T03:17:20.345Z",
              },
            },
          ],
        },
      },
    },
    {
      id: 13,
      attributes: {
        name: "Baterai Tahan Lama",
        price: 190000,
        category: "bestSellers",
        createdAt: "2023-02-13T03:39:52.290Z",
        updatedAt: "2023-02-22T14:02:25.963Z",
        publishedAt: "2023-02-13T03:39:53.453Z",
        shortDesc: "Eco-friendly reusable water bottle.",
        longDesc:
          "Reduce your environmental impact with our eco-friendly reusable water bottle. Made from high-quality materials, this bottle is durable, lightweight, and easy to carry with you wherever you go. Plus, it's leak-proof and easy to clean, making it the perfect choice for both daily use and outdoor adventures. Choose our reusable water bottle and help protect our planet.",
        image: {
          data: [
            {
              id: 6,
              attributes: {
                name: "kyle-smith-tlowJ-oYAjU-unsplash.jpg",
                alternativeText: null,
                caption: null,
                width: 3456,
                height: 5184,
                formats: {
                  thumbnail: {
                    name: "thumbnail_kyle-smith-tlowJ-oYAjU-unsplash.jpg",
                    hash: "thumbnail_kyle_smith_tlow_J_o_Y_Aj_U_unsplash_4a4ea89459",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 104,
                    height: 156,
                    size: 3.36,
                    url: "/uploads/thumbnail_kyle_smith_tlow_J_o_Y_Aj_U_unsplash_4a4ea89459.jpg",
                  },
                  large: {
                    name: "large_kyle-smith-tlowJ-oYAjU-unsplash.jpg",
                    hash: "large_kyle_smith_tlow_J_o_Y_Aj_U_unsplash_4a4ea89459",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 667,
                    height: 1000,
                    size: 59.27,
                    url: "/uploads/large_kyle_smith_tlow_J_o_Y_Aj_U_unsplash_4a4ea89459.jpg",
                  },
                  medium: {
                    name: "medium_kyle-smith-tlowJ-oYAjU-unsplash.jpg",
                    hash: "medium_kyle_smith_tlow_J_o_Y_Aj_U_unsplash_4a4ea89459",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 500,
                    height: 750,
                    size: 35.44,
                    url: "/uploads/medium_kyle_smith_tlow_J_o_Y_Aj_U_unsplash_4a4ea89459.jpg",
                  },
                  small: {
                    name: "small_kyle-smith-tlowJ-oYAjU-unsplash.jpg",
                    hash: "small_kyle_smith_tlow_J_o_Y_Aj_U_unsplash_4a4ea89459",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 333,
                    height: 500,
                    size: 18.07,
                    url: "/uploads/small_kyle_smith_tlow_J_o_Y_Aj_U_unsplash_4a4ea89459.jpg",
                  },
                },
                hash: "kyle_smith_tlow_J_o_Y_Aj_U_unsplash_4a4ea89459",
                ext: ".jpg",
                mime: "image/jpeg",
                size: 2329.76,
                url: "/uploads/kyle_smith_tlow_J_o_Y_Aj_U_unsplash_4a4ea89459.jpg",
                previewUrl: null,
                provider: "local",
                provider_metadata: null,
                createdAt: "2023-02-13T03:17:19.113Z",
                updatedAt: "2023-02-13T03:17:19.113Z",
              },
            },
          ],
        },
      },
    },
    {
      id: 14,
      attributes: {
        name: "Sepatu Olahraga",
        price: 400000,
        category: "topRated",
        createdAt: "2023-02-13T03:41:12.194Z",
        updatedAt: "2023-02-22T14:05:35.445Z",
        publishedAt: "2023-02-13T03:41:13.742Z",
        shortDesc: "Travel backpack with TSA-approved lock.",
        longDesc:
          "Stay organized and secure during your travels with our travel backpack. With ample storage space and multiple compartments, this backpack is perfect for carrying all your essentials while on the go. The built-in TSA-approved lock provides added security for your belongings, while the adjustable straps ensure a comfortable fit. Get ready for your next adventure with our travel backpack.",
        image: {
          data: [
            {
              id: 6,
              attributes: {
                name: "kyle-smith-tlowJ-oYAjU-unsplash.jpg",
                alternativeText: null,
                caption: null,
                width: 3456,
                height: 5184,
                formats: {
                  thumbnail: {
                    name: "thumbnail_kyle-smith-tlowJ-oYAjU-unsplash.jpg",
                    hash: "thumbnail_kyle_smith_tlow_J_o_Y_Aj_U_unsplash_4a4ea89459",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 104,
                    height: 156,
                    size: 3.36,
                    url: "/uploads/thumbnail_kyle_smith_tlow_J_o_Y_Aj_U_unsplash_4a4ea89459.jpg",
                  },
                  large: {
                    name: "large_kyle-smith-tlowJ-oYAjU-unsplash.jpg",
                    hash: "large_kyle_smith_tlow_J_o_Y_Aj_U_unsplash_4a4ea89459",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 667,
                    height: 1000,
                    size: 59.27,
                    url: "/uploads/large_kyle_smith_tlow_J_o_Y_Aj_U_unsplash_4a4ea89459.jpg",
                  },
                  medium: {
                    name: "medium_kyle-smith-tlowJ-oYAjU-unsplash.jpg",
                    hash: "medium_kyle_smith_tlow_J_o_Y_Aj_U_unsplash_4a4ea89459",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 500,
                    height: 750,
                    size: 35.44,
                    url: "/uploads/medium_kyle_smith_tlow_J_o_Y_Aj_U_unsplash_4a4ea89459.jpg",
                  },
                  small: {
                    name: "small_kyle-smith-tlowJ-oYAjU-unsplash.jpg",
                    hash: "small_kyle_smith_tlow_J_o_Y_Aj_U_unsplash_4a4ea89459",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 333,
                    height: 500,
                    size: 18.07,
                    url: "/uploads/small_kyle_smith_tlow_J_o_Y_Aj_U_unsplash_4a4ea89459.jpg",
                  },
                },
                hash: "kyle_smith_tlow_J_o_Y_Aj_U_unsplash_4a4ea89459",
                ext: ".jpg",
                mime: "image/jpeg",
                size: 2329.76,
                url: "/uploads/kyle_smith_tlow_J_o_Y_Aj_U_unsplash_4a4ea89459.jpg",
                previewUrl: null,
                provider: "local",
                provider_metadata: null,
                createdAt: "2023-02-13T03:17:19.113Z",
                updatedAt: "2023-02-13T03:17:19.113Z",
              },
            },
          ],
        },
      },
    },
    {
      id: 15,
      attributes: {
        name: "Jam Tangan Mewah",
        price: 290000,
        category: "topRated",
        createdAt: "2023-02-13T03:41:59.262Z",
        updatedAt: "2023-02-22T14:04:01.789Z",
        publishedAt: "2023-02-13T03:42:00.559Z",
        shortDesc: "All-natural skincare for healthy, glowing skin.",
        longDesc:
          "Take care of your skin with our all-natural skincare line. Made with only the finest ingredients, our products are gentle, effective, and safe for even the most sensitive skin. From cleansers to moisturizers, our skincare line has everything you need to achieve healthy, glowing",
        image: {
          data: [
            {
              id: 5,
              attributes: {
                name: "alrick-gillard-0mN84vxigL0-unsplash.jpg",
                alternativeText: null,
                caption: null,
                width: 4000,
                height: 6000,
                formats: {
                  thumbnail: {
                    name: "thumbnail_alrick-gillard-0mN84vxigL0-unsplash.jpg",
                    hash: "thumbnail_alrick_gillard_0m_N84vxig_L0_unsplash_5c5647a50a",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 104,
                    height: 156,
                    size: 5.04,
                    url: "/uploads/thumbnail_alrick_gillard_0m_N84vxig_L0_unsplash_5c5647a50a.jpg",
                  },
                  medium: {
                    name: "medium_alrick-gillard-0mN84vxigL0-unsplash.jpg",
                    hash: "medium_alrick_gillard_0m_N84vxig_L0_unsplash_5c5647a50a",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 500,
                    height: 750,
                    size: 55.48,
                    url: "/uploads/medium_alrick_gillard_0m_N84vxig_L0_unsplash_5c5647a50a.jpg",
                  },
                  large: {
                    name: "large_alrick-gillard-0mN84vxigL0-unsplash.jpg",
                    hash: "large_alrick_gillard_0m_N84vxig_L0_unsplash_5c5647a50a",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 667,
                    height: 1000,
                    size: 89.23,
                    url: "/uploads/large_alrick_gillard_0m_N84vxig_L0_unsplash_5c5647a50a.jpg",
                  },
                  small: {
                    name: "small_alrick-gillard-0mN84vxigL0-unsplash.jpg",
                    hash: "small_alrick_gillard_0m_N84vxig_L0_unsplash_5c5647a50a",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 333,
                    height: 500,
                    size: 28.9,
                    url: "/uploads/small_alrick_gillard_0m_N84vxig_L0_unsplash_5c5647a50a.jpg",
                  },
                },
                hash: "alrick_gillard_0m_N84vxig_L0_unsplash_5c5647a50a",
                ext: ".jpg",
                mime: "image/jpeg",
                size: 1706.93,
                url: "/uploads/alrick_gillard_0m_N84vxig_L0_unsplash_5c5647a50a.jpg",
                previewUrl: null,
                provider: "local",
                provider_metadata: null,
                createdAt: "2023-02-13T03:17:18.697Z",
                updatedAt: "2023-02-13T03:17:18.697Z",
              },
            },
          ],
        },
      },
    },
    {
      id: 16,
      attributes: {
        name: "Tas Sekolah",
        price: 220000,
        category: "topRated",
        createdAt: "2023-02-13T03:42:38.359Z",
        updatedAt: "2023-02-22T14:07:27.679Z",
        publishedAt: "2023-02-13T03:42:40.317Z",
        shortDesc: "Versatile and durable backpack for everyday use.",
        longDesc:
          "Our versatile and durable backpack is perfect for all your daily needs. With multiple compartments and pockets, you can easily organize and carry all your essentials. The sturdy and waterproof material ensures the backpack is durable and able to withstand daily wear and tear. Upgrade your everyday carry with our backpack.",
        image: {
          data: [
            {
              id: 3,
              attributes: {
                name: "vahid-kanani-qiMCJHg2vTI-unsplash.jpg",
                alternativeText: null,
                caption: null,
                width: 3917,
                height: 5354,
                formats: {
                  thumbnail: {
                    name: "thumbnail_vahid-kanani-qiMCJHg2vTI-unsplash.jpg",
                    hash: "thumbnail_vahid_kanani_qi_MCJ_Hg2v_TI_unsplash_66305e1315",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 114,
                    height: 156,
                    size: 2.87,
                    url: "/uploads/thumbnail_vahid_kanani_qi_MCJ_Hg2v_TI_unsplash_66305e1315.jpg",
                  },
                  large: {
                    name: "large_vahid-kanani-qiMCJHg2vTI-unsplash.jpg",
                    hash: "large_vahid_kanani_qi_MCJ_Hg2v_TI_unsplash_66305e1315",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 732,
                    height: 1000,
                    size: 47.5,
                    url: "/uploads/large_vahid_kanani_qi_MCJ_Hg2v_TI_unsplash_66305e1315.jpg",
                  },
                  medium: {
                    name: "medium_vahid-kanani-qiMCJHg2vTI-unsplash.jpg",
                    hash: "medium_vahid_kanani_qi_MCJ_Hg2v_TI_unsplash_66305e1315",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 549,
                    height: 750,
                    size: 28,
                    url: "/uploads/medium_vahid_kanani_qi_MCJ_Hg2v_TI_unsplash_66305e1315.jpg",
                  },
                  small: {
                    name: "small_vahid-kanani-qiMCJHg2vTI-unsplash.jpg",
                    hash: "small_vahid_kanani_qi_MCJ_Hg2v_TI_unsplash_66305e1315",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 365,
                    height: 500,
                    size: 14.45,
                    url: "/uploads/small_vahid_kanani_qi_MCJ_Hg2v_TI_unsplash_66305e1315.jpg",
                  },
                },
                hash: "vahid_kanani_qi_MCJ_Hg2v_TI_unsplash_66305e1315",
                ext: ".jpg",
                mime: "image/jpeg",
                size: 1386.01,
                url: "/uploads/vahid_kanani_qi_MCJ_Hg2v_TI_unsplash_66305e1315.jpg",
                previewUrl: null,
                provider: "local",
                provider_metadata: null,
                createdAt: "2023-02-13T03:17:16.399Z",
                updatedAt: "2023-02-13T03:17:16.399Z",
              },
            },
          ],
        },
      },
    },
    {
      id: 17,
      attributes: {
        name: "Kacamata Hitam",
        price: 390000,
        category: "topRated",
        createdAt: "2023-02-13T03:43:20.995Z",
        updatedAt: "2023-02-22T14:04:41.189Z",
        publishedAt: "2023-02-13T03:43:22.144Z",
        shortDesc: "Wireless Bluetooth speaker with crisp, clear sound.",
        longDesc:
          "Enjoy your favorite music on the go with our wireless Bluetooth speaker. With crystal-clear sound and powerful bass, this speaker delivers an immersive listening experience. Its compact design makes it easy to take with you wherever you go, and its long battery life ensures you can enjoy hours of music without interruption. Get the perfect sound quality with our Bluetooth speaker.",
        image: {
          data: [
            {
              id: 2,
              attributes: {
                name: "khaled-ghareeb-ifzilsFFqOs-unsplash.jpg",
                alternativeText: null,
                caption: null,
                width: 3871,
                height: 5568,
                formats: {
                  thumbnail: {
                    name: "thumbnail_khaled-ghareeb-ifzilsFFqOs-unsplash.jpg",
                    hash: "thumbnail_khaled_ghareeb_ifzils_F_Fq_Os_unsplash_095c3c869c",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 108,
                    height: 156,
                    size: 3.32,
                    url: "/uploads/thumbnail_khaled_ghareeb_ifzils_F_Fq_Os_unsplash_095c3c869c.jpg",
                  },
                  large: {
                    name: "large_khaled-ghareeb-ifzilsFFqOs-unsplash.jpg",
                    hash: "large_khaled_ghareeb_ifzils_F_Fq_Os_unsplash_095c3c869c",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 695,
                    height: 1000,
                    size: 47.52,
                    url: "/uploads/large_khaled_ghareeb_ifzils_F_Fq_Os_unsplash_095c3c869c.jpg",
                  },
                  medium: {
                    name: "medium_khaled-ghareeb-ifzilsFFqOs-unsplash.jpg",
                    hash: "medium_khaled_ghareeb_ifzils_F_Fq_Os_unsplash_095c3c869c",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 521,
                    height: 750,
                    size: 30.54,
                    url: "/uploads/medium_khaled_ghareeb_ifzils_F_Fq_Os_unsplash_095c3c869c.jpg",
                  },
                  small: {
                    name: "small_khaled-ghareeb-ifzilsFFqOs-unsplash.jpg",
                    hash: "small_khaled_ghareeb_ifzils_F_Fq_Os_unsplash_095c3c869c",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 347,
                    height: 500,
                    size: 16.4,
                    url: "/uploads/small_khaled_ghareeb_ifzils_F_Fq_Os_unsplash_095c3c869c.jpg",
                  },
                },
                hash: "khaled_ghareeb_ifzils_F_Fq_Os_unsplash_095c3c869c",
                ext: ".jpg",
                mime: "image/jpeg",
                size: 1156.05,
                url: "/uploads/khaled_ghareeb_ifzils_F_Fq_Os_unsplash_095c3c869c.jpg",
                previewUrl: null,
                provider: "local",
                provider_metadata: null,
                createdAt: "2023-02-13T03:17:15.811Z",
                updatedAt: "2023-02-13T03:17:15.811Z",
              },
            },
          ],
        },
      },
    },
    {
      id: 18,
      attributes: {
        name: " Jasa Catering",
        price: 600000,
        category: "topRated",
        createdAt: "2023-02-13T03:43:58.016Z",
        updatedAt: "2023-02-22T14:01:07.939Z",
        publishedAt: "2023-02-13T03:43:59.740Z",
        shortDesc: "Smartwatch with health tracking and mobile payment.",
        longDesc:
          "Stay connected and healthy with our new smartwatch. Monitor your fitness levels, heart rate, and sleep patterns with ease. With built-in mobile payment capabilities, you can leave your wallet at home and pay for your purchases with a flick of your wrist. Plus, enjoy all the features you need, from receiving notifications to streaming music. Get the most out of every day with this versatile and stylish accessory",
        image: {
          data: [
            {
              id: 1,
              attributes: {
                name: "olha-ivanova-lWeITB-GWc4-unsplash.jpg",
                alternativeText: null,
                caption: null,
                width: 4000,
                height: 6000,
                formats: {
                  thumbnail: {
                    name: "thumbnail_olha-ivanova-lWeITB-GWc4-unsplash.jpg",
                    hash: "thumbnail_olha_ivanova_l_We_ITB_G_Wc4_unsplash_862e065cb2",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 104,
                    height: 156,
                    size: 2,
                    url: "/uploads/thumbnail_olha_ivanova_l_We_ITB_G_Wc4_unsplash_862e065cb2.jpg",
                  },
                  large: {
                    name: "large_olha-ivanova-lWeITB-GWc4-unsplash.jpg",
                    hash: "large_olha_ivanova_l_We_ITB_G_Wc4_unsplash_862e065cb2",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 667,
                    height: 1000,
                    size: 29.77,
                    url: "/uploads/large_olha_ivanova_l_We_ITB_G_Wc4_unsplash_862e065cb2.jpg",
                  },
                  medium: {
                    name: "medium_olha-ivanova-lWeITB-GWc4-unsplash.jpg",
                    hash: "medium_olha_ivanova_l_We_ITB_G_Wc4_unsplash_862e065cb2",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 500,
                    height: 750,
                    size: 18.83,
                    url: "/uploads/medium_olha_ivanova_l_We_ITB_G_Wc4_unsplash_862e065cb2.jpg",
                  },
                  small: {
                    name: "small_olha-ivanova-lWeITB-GWc4-unsplash.jpg",
                    hash: "small_olha_ivanova_l_We_ITB_G_Wc4_unsplash_862e065cb2",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 333,
                    height: 500,
                    size: 10.07,
                    url: "/uploads/small_olha_ivanova_l_We_ITB_G_Wc4_unsplash_862e065cb2.jpg",
                  },
                },
                hash: "olha_ivanova_l_We_ITB_G_Wc4_unsplash_862e065cb2",
                ext: ".jpg",
                mime: "image/jpeg",
                size: 747.61,
                url: "/uploads/olha_ivanova_l_We_ITB_G_Wc4_unsplash_862e065cb2.jpg",
                previewUrl: null,
                provider: "local",
                provider_metadata: null,
                createdAt: "2023-02-13T03:17:12.975Z",
                updatedAt: "2023-02-13T03:17:12.975Z",
              },
            },
          ],
        },
      },
    },
    {
      id: 19,
      attributes: {
        name: "Fitness Tracker Watch",
        price: 444000,
        category: "topRated",
        createdAt: "2023-02-13T03:46:12.446Z",
        updatedAt: "2023-02-22T14:03:08.688Z",
        publishedAt: "2023-02-13T03:46:47.377Z",
        shortDesc: "Gourmet coffee beans for a rich, flavorful brew.",
        longDesc:
          "Start your day off right with our gourmet coffee beans. Carefully selected and roasted to perfection, these beans produce a rich, flavorful brew that will satisfy even the most discerning coffee connoisseur. Plus, our beans are sustainably sourced and support local farmers, making them the perfect choice for anyone who cares about their coffee and the environment.",
        image: {
          data: [
            {
              id: 4,
              attributes: {
                name: "judeus-samson-y2ny77b5sU0-unsplash.jpg",
                alternativeText: null,
                caption: null,
                width: 3313,
                height: 5184,
                formats: {
                  thumbnail: {
                    name: "thumbnail_judeus-samson-y2ny77b5sU0-unsplash.jpg",
                    hash: "thumbnail_judeus_samson_y2ny77b5s_U0_unsplash_21bc2fd23f",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 100,
                    height: 156,
                    size: 5.3,
                    url: "/uploads/thumbnail_judeus_samson_y2ny77b5s_U0_unsplash_21bc2fd23f.jpg",
                  },
                  small: {
                    name: "small_judeus-samson-y2ny77b5sU0-unsplash.jpg",
                    hash: "small_judeus_samson_y2ny77b5s_U0_unsplash_21bc2fd23f",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 319,
                    height: 500,
                    size: 33.84,
                    url: "/uploads/small_judeus_samson_y2ny77b5s_U0_unsplash_21bc2fd23f.jpg",
                  },
                  large: {
                    name: "large_judeus-samson-y2ny77b5sU0-unsplash.jpg",
                    hash: "large_judeus_samson_y2ny77b5s_U0_unsplash_21bc2fd23f",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 639,
                    height: 1000,
                    size: 101,
                    url: "/uploads/large_judeus_samson_y2ny77b5s_U0_unsplash_21bc2fd23f.jpg",
                  },
                  medium: {
                    name: "medium_judeus-samson-y2ny77b5sU0-unsplash.jpg",
                    hash: "medium_judeus_samson_y2ny77b5s_U0_unsplash_21bc2fd23f",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 479,
                    height: 750,
                    size: 64.86,
                    url: "/uploads/medium_judeus_samson_y2ny77b5s_U0_unsplash_21bc2fd23f.jpg",
                  },
                },
                hash: "judeus_samson_y2ny77b5s_U0_unsplash_21bc2fd23f",
                ext: ".jpg",
                mime: "image/jpeg",
                size: 1614.1,
                url: "/uploads/judeus_samson_y2ny77b5s_U0_unsplash_21bc2fd23f.jpg",
                previewUrl: null,
                provider: "local",
                provider_metadata: null,
                createdAt: "2023-02-13T03:17:17.380Z",
                updatedAt: "2023-02-13T03:17:17.380Z",
              },
            },
          ],
        },
      },
    },
  ],
  meta: {
    pagination: {
      page: 1,
      pageSize: 25,
      pageCount: 1,
      total: 18,
    },
  },
};

export type Item = typeof allProducts.data[0];
